name: "Alpha Artifacts"
on:
    push:
        branches: [dev]
jobs:
    test-tauri:
        strategy:
            fail-fast: false
            matrix:
                    include:
                    - os: macos-latest
                      NAME: mac
                    - os: ubuntu-latest
                      NAME: linux
                    - os: windows-latest
                      NAME: windows
        runs-on: ${{ matrix.os}}
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 15
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install webkit2gtk (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y webkit2gtk-4.0
            - name: install app dependencies and build it
              run: npm ci && npm run build:alpha
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Remove build folder
              uses: JesseTG/rm@v1.0.2
              with:
                  path: src-tauri/target/release/build
            - name: Remove deps folder
              uses: JesseTG/rm@v1.0.2
              with:
                  path: src-tauri/target/release/deps
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: authme-lite-latest-alpha-${{matrix.NAME}}-x64-installer-portable
                  path: src-tauri/target/release
