name: Alpha Artifacts
on:
  push:
    branches:
      - dev
jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            NAME: mac
          - os: ubuntu-latest
            NAME: linux
          - os: windows-latest
            NAME: windows
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install webkit2gtk (ubuntu only)
        if: matrix.NAME == 'linux'
        run: >
          sudo apt-get update

          sudo apt-get install -y webkit2gtk-4.0
      - name: Install app dependencies and build it
        run: npm ci && npm run build:alpha
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove useless folders
        run: >
          rm -rf core/target/release/build

          rm -rf core/target/release/deps
          
          rm -rf core/target/release/bundle
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: authme-lite-latest-alpha-${{matrix.NAME}}-x64-installer-portable
          path: core/target/release
